### ISSUE TITLE
Optimize: Serialize event handlers as attributes, remove from hydrate functions

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/x#98]

**Comment by DylanPiercey** [comment]
Maybe this is revisited but in all attempts it seems to be worse on the output side.

* Serialized scripts were larger because we had to serialize the function call and it's args (which was more than REGISTER_ID SCOPE_ID pairs we have for effects)
* A main driver was to remove the initial walk but that also increased serialized size by having to put dom information into the serialized scope instead of on markers (and we're already walking for comments and such for the async reorder runtime).
